// Generates the SCSS theme maps and the TypeScript token module from tokens/themes.json,
// so the palette has a single source of truth.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const pkg = fileURLToPath(new URL('../packages/onesmallui/', import.meta.url));
const themes = JSON.parse(readFileSync(`${pkg}tokens/themes.json`, 'utf8'));
const banner = '// AUTO-GENERATED by scripts/build-tokens.mjs from tokens/themes.json. Do not edit.\n';

const scssMap = (name, t) =>
  `$theme-${name}: (\n${Object.entries(t)
    .map(([k, v]) => `  '${k}': ${v},`)
    .join('\n')}\n) !default;\n`;

writeFileSync(
  `${pkg}scss/abstracts/_themes.scss`,
  banner + '\n' + Object.entries(themes).map(([n, t]) => scssMap(n, t)).join('\n'),
);

writeFileSync(
  `${pkg}src/tokens.ts`,
  banner +
    '\n/** Theme color tokens. Each key is exposed as a CSS custom property `--os-<key>`. */\n' +
    `export const themes = ${JSON.stringify(themes, null, 2)} as const;\n\n` +
    'export type ThemeName = keyof typeof themes;\n' +
    'export type ColorToken = keyof (typeof themes)["light"];\n\n' +
    '/** Returns a `var(--os-*)` reference for a color token. */\n' +
    'export const cssVar = (token: ColorToken): string => `var(--os-${token})`;\n',
);
console.log('Tokens generated.');
